# Generated by Django 5.1.4 on 2026-06-13 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manufacturing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('sku', models.CharField(max_length=40, unique=True)),
                ('product_type', models.CharField(choices=[('stockable', 'Stockable'), ('consumable', 'Consumable')], default='stockable', max_length=12)),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('strategy', models.CharField(choices=[('mts', 'Make To Stock'), ('mto', 'Make To Order')], default='mts', help_text='MTS: replenish before demand. MTO: replenish on customer order.', max_length=4)),
                ('procure_on_demand', models.BooleanField(default=True)),
                ('procurement_type', models.CharField(choices=[('buy', 'Purchase'), ('manufacture', 'Manufacture')], default='buy', max_length=12)),
                ('on_hand', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('reserved', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bom', models.ForeignKey(blank=True, help_text='Default BoM used when manufacturing this product.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='manufacturing.bom')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
