# Generated by Django 5.1.4 on 2026-06-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufacture_lead_days',
            field=models.PositiveIntegerField(default=5, help_text='Days to build this product (used for forecasting).'),
        ),
        migrations.AddField(
            model_name='product',
            name='reorder_point',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Min free stock to keep (MTS). Below this → replenish.', max_digits=12),
        ),
    ]
