# Generated by Django 5.1.4 on 2026-06-13 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trigger', models.CharField(help_text='e.g. SO00007 confirmed', max_length=60)),
                ('required_qty', models.DecimalField(decimal_places=2, max_digits=12)),
                ('free_qty', models.DecimalField(decimal_places=2, max_digits=12)),
                ('shortage', models.DecimalField(decimal_places=2, max_digits=12)),
                ('action', models.CharField(choices=[('purchase', 'Purchase Order'), ('manufacture', 'Manufacturing Order'), ('none', 'No Action (in stock)')], max_length=12)),
                ('result_ref', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
