# Generated by Django 6.0.6 on 2026-06-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_add_notes_and_delivery_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='created_by',
            field=models.CharField(default='System', max_length=100, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='expected_receipt_date',
            field=models.DateField(blank=True, null=True, verbose_name='Expected Receipt Date'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='po_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='PO Number'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Unit Cost in INR (₹)', max_digits=10, verbose_name='Unit Cost'),
        ),
    ]
