# Generated by Django 6.0.6 on 2026-06-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_remove_purchaseorderitem_unit_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='responsible_person',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Responsible Person'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vendor_address',
            field=models.TextField(blank=True, default='', verbose_name='Vendor Address'),
        ),
    ]
