# Generated by Django 6.0.6 on 2026-06-13 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('movement_type', models.CharField(choices=[('Sales Delivery', 'Sales Delivery'), ('Purchase Receipt', 'Purchase Receipt'), ('Manufacturing Consumption', 'Manufacturing Consumption'), ('Manufacturing Production', 'Manufacturing Production'), ('Manual Adjustment', 'Manual Adjustment')], max_length=50)),
                ('quantity_change', models.IntegerField()),
                ('source_document', models.CharField(max_length=100)),
                ('user', models.CharField(default='System', max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='products.product')),
            ],
        ),
    ]
