# Generated by Django 6.0.6 on 2026-06-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockledgerentry',
            name='balance_after',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Balance After'),
        ),
        migrations.AlterField(
            model_name='stockledgerentry',
            name='quantity_change',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantity Change'),
        ),
    ]
