# Generated by Django 6.0.6 on 2026-06-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturingorder',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
