# Generated by Django 6.0.6 on 2026-06-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0003_alter_manufacturingorder_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bomoperation',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='bomoperation',
            name='name',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='name',
        ),
        migrations.AddField(
            model_name='bom',
            name='bom_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='BoM Code'),
        ),
        migrations.AddField(
            model_name='bom',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='bom',
            name='quantity_produced',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='Quantity Produced'),
        ),
        migrations.AddField(
            model_name='bom',
            name='version',
            field=models.CharField(default='1.0', max_length=10, verbose_name='Version'),
        ),
        migrations.AddField(
            model_name='bomoperation',
            name='duration_minutes',
            field=models.IntegerField(default=30, verbose_name='Duration (minutes)'),
        ),
        migrations.AddField(
            model_name='bomoperation',
            name='operation_name',
            field=models.CharField(default='', max_length=100, verbose_name='Operation Name'),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='mo_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='MO Number'),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='planned_date',
            field=models.DateField(blank=True, null=True, verbose_name='Planned Date'),
        ),
        migrations.AddField(
            model_name='manufacturingorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Completed At'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='duration_minutes',
            field=models.IntegerField(default=30, verbose_name='Duration (minutes)'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='operation',
            field=models.CharField(default='', max_length=100, verbose_name='Operation'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Started At'),
        ),
        migrations.AlterField(
            model_name='bomcomponent',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='bomoperation',
            name='work_center',
            field=models.CharField(max_length=100, verbose_name='Work Center'),
        ),
        migrations.AlterField(
            model_name='manufacturingorder',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='work_center',
            field=models.CharField(max_length=100, verbose_name='Work Center'),
        ),
    ]
