# Generated by Django 6.0.6 on 2026-06-13 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0004_remove_bomoperation_duration_and_more'),
        ('products', '0003_remove_product_procure_type_product_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='real_duration_minutes',
            field=models.IntegerField(default=0, verbose_name='Real Duration (minutes)'),
        ),
        migrations.CreateModel(
            name='ManufacturingOrderComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_consume', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='To Consume')),
                ('consumed', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Consumed')),
                ('manufacturing_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='manufacturing.manufacturingorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
