# Generated by Django 6.0.6 on 2026-06-14 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0005_workorder_real_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bom',
            name='reference',
            field=models.CharField(blank=True, default='', max_length=8, verbose_name='Reference'),
        ),
    ]
