# Generated by Django 6.0.6 on 2026-06-13 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('module', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('user', models.CharField(default='System', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('low_stock', 'Low Stock Alert'), ('procurement_created', 'Procurement Triggered'), ('purchase_received', 'Purchase Shipment Received'), ('sales_delivered', 'Sales Delivery Dispatched'), ('manufacturing_completion', 'Manufacturing Completed')], max_length=50)),
                ('message', models.TextField()),
                ('read', models.BooleanField(default=False)),
            ],
        ),
    ]
