# Generated by Django 6.0.6 on 2026-06-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='auditlog',
            name='object_id',
            field=models.IntegerField(blank=True, help_text='The primary key of the affected record', null=True, verbose_name='Object ID'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='object_type',
            field=models.CharField(blank=True, help_text='The model/entity this log refers to (e.g. SalesOrder, Product)', max_length=100, null=True, verbose_name='Object Type'),
        ),
    ]
