# Generated by Django 6.0.6 on 2026-06-14 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_auditlog_options_auditlog_object_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('Create', 'Create'), ('Update', 'Update'), ('Delete', 'Delete')], default='Create', max_length=20, verbose_name='Action Type'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='field_changed',
            field=models.CharField(blank=True, default='-', max_length=50, verbose_name='Field Changed'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='new_value',
            field=models.CharField(blank=True, default='-', max_length=100, verbose_name='New Value'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='old_value',
            field=models.CharField(blank=True, default='-', max_length=100, verbose_name='Old Value'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='record_id',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Record ID'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='record_type',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Record Type'),
        ),
    ]
