# Generated by Django 5.1.4 on 2026-06-13 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('module', models.CharField(db_index=True, max_length=30)),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('status', 'Status Change'), ('stock', 'Stock Change'), ('price', 'Price Update'), ('delivery', 'Delivery'), ('procurement', 'Procurement')], db_index=True, max_length=20)),
                ('model', models.CharField(max_length=60)),
                ('object_ref', models.CharField(blank=True, max_length=120)),
                ('field', models.CharField(blank=True, max_length=60)),
                ('old_value', models.CharField(blank=True, max_length=255)),
                ('new_value', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
    ]
