# Generated by Django 6.0.6 on 2026-06-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total Amount in INR (₹)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='Unit Price in INR (₹)', max_digits=10),
        ),
    ]
