# Generated by Django 6.0.6 on 2026-06-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_salesorder_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='expected_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
