# Generated by Django 6.0.6 on 2026-06-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_add_notes_and_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='created_by',
            field=models.CharField(default='System', max_length=100, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='order_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Order Number'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
