# Generated by Django 6.0.6 on 2026-06-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_salesorder_created_by_salesorder_order_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='customer_address',
            field=models.TextField(blank=True, default='', verbose_name='Customer Address'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='sales_person',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Sales Person'),
        ),
    ]
