# Generated by Django 6.0.6 on 2026-06-13 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(choices=[('Furniture', 'Furniture'), ('Components', 'Components')], default='Furniture', max_length=50)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sales_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('on_hand', models.IntegerField(default=0)),
                ('reserved', models.IntegerField(default=0)),
                ('procure_strategy', models.CharField(choices=[('MTS', 'Make To Stock (MTS)'), ('MTO', 'Make To Order (MTO)')], default='MTS', max_length=10)),
                ('procure_type', models.CharField(choices=[('Manufacturing', 'Manufacturing'), ('Purchase', 'Purchase'), ('None', 'None')], default='None', max_length=20)),
                ('vendor', models.CharField(blank=True, max_length=150, null=True)),
                ('reorder_threshold', models.IntegerField(default=5)),
                ('status', models.CharField(default='Active', max_length=20)),
            ],
        ),
    ]
