# Generated by Django 6.0.6 on 2026-06-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Cost Price in INR (₹)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='sales_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Sales Price in INR (₹)', max_digits=10),
        ),
    ]
