# Generated by Django 6.0.6 on 2026-06-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_cost_price_alter_product_sales_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='procure_type',
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='procurement_type',
            field=models.CharField(choices=[('Manufacturing', 'Manufacturing'), ('Purchase', 'Purchase'), ('None', 'None')], default='None', max_length=20, verbose_name='Procurement Type'),
        ),
        migrations.AddField(
            model_name='product',
            name='uom',
            field=models.CharField(default='Units', max_length=50, verbose_name='Unit of Measure'),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='reorder_threshold',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=10, verbose_name='Reorder Point'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Low Stock', 'Low Stock'), ('Inactive', 'Inactive')], default='Active', max_length=20),
        ),
    ]
